# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4b02c556d8b0c0144ae6c265ec50331d4bce32fe8fec988ae4af1958afeeeafa428ff022b485430242a99c5f4c579c3f4ee05ac39a4a234ecb09f93254fcaaa

test:
  secret_key_base: 302f9e6f82437dd24f3b0ee0327e2a41937c845c3b967cad404afc0b74ca3ae55920ccfc5e4997fabe1515cb3706738bb417ae8600db13c08d9c0ff4090a1fbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
